global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'myapp'
    static_configs:
      - targets: ['myapp:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.17.0.1:9100']
